spring:
  application:
    name: config-service

  profiles:
    active: local

  cloud:
    config.server.git:
      uri: https://github.com/Akshityadav370/distributed-lovable-clone-config-server
      username: Akshityadav370
      default-label: main

server.port: 8888